### ISSUE TITLE
Mac Silicon - cloning not working - failing on glm_module

### ISSUE THREAD

**Issue by hydrazoan** [aaronaanderson/Terrain#3]
Hi

When I try the instructions for Mac, I get 

alexsaville@MacBook-Pro documents % cd Terrain                             
alexsaville@MacBook-Pro Terrain % git clone https://github.com/aaronaanderson/Terrain
Cloning into 'Terrain'...
remote: Enumerating objects: 936, done.
remote: Counting objects: 100% (363/363), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 936 (delta 255), reused 277 (delta 173), pack-reused 573 (from 1)
Receiving objects: 100% (936/936), 496.24 KiB | 1.32 MiB/s, done.
Resolving deltas: 100% (661/661), done.
alexsaville@MacBook-Pro Terrain % git submodule update --init --recursive
Submodule 'JUCE' (https://github.com/juce-framework/JUCE.git) registered for path 'JUCE'
Submodule 'PerlinNoise' (https://github.com/Reputeless/PerlinNoise.git) registered for path 'PerlinNoise'
Submodule 'glm_module/glm' (git@github.com:g-truc/glm.git) registered for path 'glm_module/glm'
Cloning into '/Users/alexsaville/Documents/Terrain/JUCE'...
Cloning into '/Users/alexsaville/Documents/Terrain/PerlinNoise'...
Cloning into '/Users/alexsaville/Documents/Terrain/glm_module/glm'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:g-truc/glm.git' into submodule path '/Users/alexsaville/Documents/Terrain/glm_module/glm' failed
Failed to clone 'glm_module/glm'. Retry scheduled
Cloning into '/Users/alexsaville/Documents/Terrain/glm_module/glm'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:g-truc/glm.git' into submodule path '/Users/alexsaville/Documents/Terrain/glm_module/glm' failed
Failed to clone 'glm_module/glm' a second time, aborting
alexsaville@MacBook-Pro Terrain %

**Comment by therealfumbles** [comment]
Clone again but before running `git submodule update --init --recursive` edit .gitmodules and change

`git@github.com:g-truc/glm.git`

to

`https://github.com/g-truc/glm.git`

**Comment by hydrazoan** [comment]
Thanks for getting back to me so promptly.

in the .gitmodules file?

`[submodule "JUCE"]
	path = JUCE
	url = https://github.com/juce-framework/JUCE.git
[submodule "glm_module/glm"]
	path = glm_module/glm
	url = https://github.com/g-truc/glm.git
[submodule "PerlinNoise"]
	path = PerlinNoise
	url = https://github.com/Reputeless/PerlinNoise.git
`

<img width="773" alt="Screenshot 2024-10-20 at 12 22 36" src="https://github.com/user-attachments/assets/23fb1760-a498-453c-99cd-f37c71109e2c">

I've just tried that and I get:

alexsaville@MacBook-Pro documents % git clone https://github.com/aaronaanderson/Terrain
Cloning into 'Terrain'...
remote: Enumerating objects: 936, done.
remote: Counting objects: 100% (363/363), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 936 (delta 255), reused 277 (delta 173), pack-reused 573 (from 1)
Receiving objects: 100% (936/936), 496.24 KiB | 4.21 MiB/s, done.
Resolving deltas: 100% (661/661), done.
alexsaville@MacBook-Pro documents % git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git
alexsaville@MacBook-Pro documents %

**Comment by therealfumbles** [comment]
You missed a step. You have to cd into the Terrain folder before running  `git submodule update --init --recursive`.

**Comment by hydrazoan** [comment]
Ah, yes, that would be it! Thanks :)

**Comment by hydrazoan** [comment]
Hi again
I get the following:
 
alexsaville@MacBook-Pro Terrain % mkdir build           
alexsaville@MacBook-Pro Terrain % cmake -B ./build -S . -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Volumes/Audio Plugin Files/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Volumes/Audio Plugin Files/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - broken
CMake Error at /opt/homebrew/Cellar/cmake/3.26.4/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/Volumes/Audio Plugin Files/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/alexsaville/documents/Terrain/build/CMakeFiles/CMakeScratch/TryCompile-OR9bdP
    
    Run Build Command(s):/opt/homebrew/Cellar/cmake/3.26.4/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_ec2d9/fast && /Volumes/Audio Plugin Files/Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_ec2d9.dir/build.make CMakeFiles/cmTC_ec2d9.dir/build
    make: /Volumes/Audio: No such file or directory
    make: *** [cmTC_ec2d9/fast] Error 1
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
alexsaville@MacBook-Pro Terrain % 

Thanks

**Comment by hydrazoan** [comment]
Presumably there is some way to point it to the location of the compiler, as it seems to be failing because of the spaces in the volume name?
TIA

**Comment by therealfumbles** [comment]
It does look like the spaces are the issue. I've never ran Xcode outside of /Applications so this is a new one for me.

Try running `xcode-select --print-path` and see if it prints the path with quotes at either end. My guess is it won't have the quotes. In that case try:

`xcode-select --switch  /Volumes/Audio\ Plugin\ Files/Applications/Xcode.app`

The backslashes escape the spaces and should fix the path.

**Comment by hydrazoan** [comment]
First I tried exactly as you suggested, but after it came up with the same results, I realised that I've got Xcode.app installed on multiple volumes, with a symlink to the "old" version - at least I think it was the old version - so I tried the following adapting your suggestion, using the right volume.
alexsaville@MacBook-Pro Terrain % sudo xcode-select --switch  /Volumes/Additional-Applications/Applications/Xcode.app
Password:
alexsaville@MacBook-Pro Terrain % xcode-select --print-path
/Volumes/Additional-Applications/Applications/Xcode.app/Contents/Developer
alexsaville@MacBook-Pro Terrain % cmake -B ./build -S . -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Volumes/Audio Plugin Files/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Volumes/Audio Plugin Files/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks/OpenGL.framework   
-- Configuring juceaide
-- Building juceaide
-- Exporting juceaide
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done (57.9s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/alexsaville/documents/Terrain/build
alexsaville@MacBook-Pro Terrain % 
It might well be that I didn't need the switch, just to get rid of the old version, change the symlink, and retry, but it seems to have got its head stuck into the Audio Plugin Files version, and so I've got symlinks in Applications on both the main volume and that one, pointing to Xcode.App in the Additional-Applications volume.
I have a suspicion I might need to start the whole thing from scratch.

**Comment by hydrazoan** [comment]
Woo hoo! starting again worked - thanks

**Comment by therealfumbles** [comment]
Nice :)

**Comment by aaronaanderson** [comment]
I've updated the .gitmodules from the SSH link to the HTTPS link, should be good to go now! Thank you @therealfumbles for your help here.
