### ISSUE TITLE
Inconsistent resizing

### ISSUE THREAD

**Issue by Andreya-Autumn** [aaronaanderson/Terrain#6]
The width/height proportion of the UI isn't locked while resizing, which can look rather odd. Especially as only some UI components resize proportionally. If you mess around a little you can get things into this state: 😆 
<img width="293" alt="smol" src="https://github.com/user-attachments/assets/d15bad1b-6fc0-40cc-8b61-0c2cf54abbcf">

Maybe this is on your list already. Thought I'd just drop this here in case.

**Comment by aaronaanderson** [comment]
Thank you for finding this and reporting!

**Comment by aaronaanderson** [comment]
Which DAW were you in out of curiosity? The resize limits I had in place should have prevented this. Either way, fixed in 1.2.2: https://github.com/aaronaanderson/Terrain/releases/tag/1.2.2
