### ISSUE TITLE
Cannot compile on Debian Bookworm

### ISSUE THREAD

**Issue by erwan35** [aaronaanderson/Terrain#8]
Hello,

Thanks for your synth that sounds really interesting !

I was able to test it with the .deb you have provided in https://github.com/aaronaanderson/Terrain/issues/1

But the compilation is failing here.

[compile_out.txt](https://github.com/user-attachments/files/17686609/compile_out.txt)

Cheers
Erwan

**Comment by erwan35** [comment]
I have just seen that you were also providing .deb in https://github.com/aaronaanderson/Terrain/releases :)

**Comment by aaronaanderson** [comment]
Thank you! Should be fixed in the main branch now.

**Comment by erwan35** [comment]
I had to switch to 
COMPILE_WARNING_AS_ERROR OFF  
in CMakeLists.txt
